import requests
from dotenv import load_dotenv
import os
import openai

# Load environment variables from the .env file
load_dotenv()

# Get the OPENAI_API_KEY environment variable
api_key = os.environ.get('OPENAI_API_KEY')
if api_key is None:
    raise ValueError("OPENAI_API_KEY environment variable not set")

# Instantiate the OpenAI client with the API key
client = openai.OpenAI(api_key=api_key)

# Make a completion request
completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"}
  ]
)

# Print the response
print(completion.choices[0].message)

# def query_openai(prompt, api_key, model="gpt-3.5-turbo", max_tokens=150):
#     """
#     Queries the OpenAI API with the given prompt.

#     :param prompt: The prompt to send to the API.
#     :param api_key: Your OpenAI API key.
#     :param model: The model to use for the query. Defaults to 'text-davinci-003'.
#     :param max_tokens: The maximum number of tokens to generate. Defaults to 150.
#     :return: The text generated by the API.
#     """
#     url = "https://api.openai.com/v1/engines/{}/completions".format(model)

#     headers = {
#         "Authorization": f"Bearer {api_key}",
#         "Content-Type": "application/json"
#     }

#     data = {
#         "prompt": prompt,
#         "max_tokens": max_tokens
#     }

#     response = requests.post(url, headers=headers, json=data)
#     response_data = response.json()

#     # Check if the request was successful
#     if response.status_code == 200:
#         # Return the text generated by the model
#         return response_data.get("choices", [{}])[0].get("text", "").strip()
#     else:
#         # Return the error message
#         return "Error: " + response_data.get("error", {}).get("message", "Unknown error")

# # Example usage
# api_key = os.getenv('ai_key')  # Replace with your actual API key
# print('this is the API key: ')
# prompt = "Translate the following English text to French: 'Hello, how are you?'"
# result = query_openai(prompt, api_key)
# print(result)
